SRCROOT := $(CURDIR)
LIBEXECPATH := $(SDKROOT)/usr/local/libexec

install:
	install -d $(DESTDIR)/$(LIBEXECPATH)
	install -m 755 $(SRCROOT)/availability.pl $(DESTDIR)/$(LIBEXECPATH)/availability.pl

all:
	@echo Nothing to build

clean:
	@echo Nothing to clean
