PROG := lorder

all:
	@echo "Nothing to do"

install:
	install -d $(DESTDIR)/$(DEVELOPER_DIR)/usr/bin
	install -m 755 $(PROG).sh $(DESTDIR)/$(DEVELOPER_DIR)/usr/bin/$(PROG)

clean:
	@echo "Nothing to do"
